function generate_supplement_tex(target_path)
% generate_supplement_tex  Build standalone IEEE TWC supplement with full per-link tables.
%
%   Matches main_final.tex table formatting verbatim:
%     * N1 @ 142 GHz layout (tab:LSPs)   -> p{0.6 cm}... column spec
%     * U3 and N3 cross-processing       -> full \columncolor{gray!20} on
%                                           "orig.\ (U1/N1)" columns and
%                                           !{\vrule width 1.2pt} separators
%
%   Reads values from figures/matlab/table{04,05,08,09,10,11}.csv.
%
%   Target path is resolved from:
%     1. Explicit target_path arg (if provided)
%     2. paths().paper_src_supp_path (env var PAPER_SUPP_PATH or
%        PAPER_TREE_DIR/supplement.tex)
%     3. Falls back to figures/matlab/supplement.tex (local; does NOT
%        overwrite the paper tree).

U = paths();
csv_dir = U.out_dir;
if nargin < 1 || isempty(target_path)
    if ~isempty(U.paper_src_supp_path)
        target_path = U.paper_src_supp_path;
    else
        target_path = fullfile(csv_dir, 'supplement.tex');
        fprintf('generate_supplement_tex: PAPER_SUPP_PATH not set; writing locally to %s\n', target_path);
    end
end

blocks = {};
blocks{end+1} = header_block();

% N1 and U1 standalone tables are intentionally omitted. The N1 values are
% already embedded in the N3 tables as the ``NYU orig. (N1)'' column, and
% U1 values are embedded in U3 tables as the ``USC orig. (U1)'' column.
% Listing them standalone would duplicate content.

blocks{end+1} = cross_section( ...
    fullfile(csv_dir, 'table08_U3_145.csv'), ...
    '145', 'U3_145_full', ...
    {'NYU thres', 'USC thres', 'USC orig.\ (U1)'}, ...
    'Full \textbf{U3 @ 145.5 GHz}: Point data table for USC data processed using NYU-replicated USC processing methods with both NYU''s max(25 dB below local PDP peak, 5 dB above noise floor) delay-domain threshold w/ 10 dB SLT and USC''s 12 dB above global max noise floor threshold.', ...
    'USC replicated NYU processing methods, USC Data \textbf{(U3) @ 145.5 GHz}', ...
    'u3_145');

blocks{end+1} = cross_section( ...
    fullfile(csv_dir, 'table09_U3_7.csv'), ...
    '6.75', 'U3_7_full', ...
    {'NYU thres', 'USC thres', 'USC orig.\ (U1)'}, ...
    'Full \textbf{U3 @ 6.75 GHz}: Point data table for USC data processed using NYU-replicated USC processing methods. Column definitions identical to Table~\ref{tab:U3_145_full}.', ...
    'USC replicated NYU processing methods, USC Data \textbf{(U3) @ 6.75 GHz}', ...
    'u3_7');

blocks{end+1} = cross_section( ...
    fullfile(csv_dir, 'table10_N3_142.csv'), ...
    '142', 'N3_142_full', ...
    {'USC thres', 'NYU thres', 'NYU orig.\ (N1)'}, ...
    'Full \textbf{N3 @ 142 GHz}: Point data table for NYU data processed using USC-replicated NYU processing methods.', ...
    'NYU replicated USC processing methods, NYU Data \textbf{(N3) @ 142 GHz}', ...
    'n3_142');

blocks{end+1} = cross_section( ...
    fullfile(csv_dir, 'table11_N3_7.csv'), ...
    '6.75', 'N3_7_full', ...
    {'USC thres', 'NYU thres', 'NYU orig.\ (N1)'}, ...
    'Full \textbf{N3 @ 6.75 GHz}: Point data table for NYU data processed using USC-replicated NYU processing methods. Column definitions identical to Table~\ref{tab:N3_142_full}.', ...
    'NYU replicated USC processing methods, NYU Data \textbf{(N3) @ 6.75 GHz}', ...
    'n3_7');

blocks{end+1} = footer_block();

fid = fopen(target_path, 'w');
if fid == -1, error('Cannot open %s', target_path); end
fprintf(fid, '%s', strjoin(blocks, sprintf('\n\n')));
fclose(fid);
fprintf('generate_supplement_tex: wrote %s\n', target_path);
end

% ------------------------------------------------------------------ %
function s = header_block()
s = [
    sprintf('%% AUTO-GENERATED by matlab/tools/generate_supplement_tex.m\n') ...
    sprintf('%% Do not edit by hand -- rerun after run_all(''rebuild'').\n') ...
    sprintf('%% Generated %s\n\n', datestr(now, 'yyyy-mm-dd HH:MM:SS')) ...
    sprintf('\\documentclass[journal]{IEEEtran}\n') ...
    sprintf('\\IEEEoverridecommandlockouts\n') ...
    sprintf('\\usepackage{amsmath,amssymb,amsfonts}\n') ...
    sprintf('\\usepackage{graphicx}\n') ...
    sprintf('\\usepackage{textcomp}\n') ...
    sprintf('\\usepackage[table]{xcolor}\n') ...
    sprintf('\\usepackage{bm}\n') ...
    sprintf('\\usepackage{tabularx}\n') ...
    sprintf('\\usepackage{makecell}\n') ...
    sprintf('\\usepackage{array}\n') ...
    sprintf('\\usepackage{multirow}\n') ...
    sprintf('\\usepackage{colortbl}\n') ...
    sprintf('\\usepackage{booktabs}\n') ...
    sprintf('\\usepackage{hyperref}\n') ...
    sprintf('\\usepackage{gensymb}\n\n') ...
    sprintf('\\title{Supplementary Material for ``Pooling of Multi-Institutional Radio Propagation Empirical Data with Cross-Processing Validation for 6G AI/ML Channel Modeling''''}\n\n') ...
    sprintf('\\author{Dipankar~Shakya,\n') ...
    sprintf('Mingjun~Ying,\n') ...
    sprintf('Naveed~A.~Abbasi,\n') ...
    sprintf('Jorge~Gomez-Ponce,~\\IEEEmembership{Senior~Member,~IEEE,}\n') ...
    sprintf('Xingchen~Liu,\n') ...
    sprintf('Xinquan~Wang,\n') ...
    sprintf('Daniel~Abraham,\n') ...
    sprintf('Theodore~S.~Rappaport,~\\IEEEmembership{Life~Fellow,~IEEE,}\n') ...
    sprintf('and~Andreas~F.~Molisch,~\\IEEEmembership{Fellow,~IEEE}}\n\n') ...
    sprintf('\\begin{document}\n\\maketitle\n\n') ...
    sprintf('\\section*{Overview}\n') ...
    sprintf('This supplementary document accompanies the manuscript ``Pooling of Multi-Institutional Radio Propagation Empirical Data with Cross-Processing Validation for 6G AI/ML Channel Modeling.'''' It provides the complete per-link point-data tables that were abbreviated in the main paper due to page-length constraints. All entries are produced by the same end-to-end processing pipeline (\\texttt{matlab/run\\_all.m}) that generates the aggregate statistics, figures, and summary tables in the main manuscript; the datasets tabulated here are:\n') ...
    sprintf('\\begin{itemize}\n') ...
    sprintf('  \\item \\textbf{U3}---USC data processed with the USC methodology and with NYU''s delay-domain threshold applied, at 145.5~GHz and 6.75~GHz (Tables~\\ref{tab:U3_145_full} and \\ref{tab:U3_7_full}). The ``USC orig.\\ (U1)'' column gives the institution-consistent U1 reference values.\n') ...
    sprintf('  \\item \\textbf{N3}---NYU data processed with the USC-replicated methodology and with USC''s threshold applied, at 142~GHz and 6.75~GHz (Tables~\\ref{tab:N3_142_full} and \\ref{tab:N3_7_full}). The ``NYU orig.\\ (N1)'' column gives the institution-consistent N1 reference values.\n') ...
    sprintf('\\end{itemize}\n') ...
    sprintf('Table, column, and threshold definitions follow Section~III of the main paper. Processing-method details for the \\emph{NYU~SUM} and \\emph{USC~perDelayMax} omni~PDP syntheses, and the corresponding noise-floor and delay-gating conventions, are documented therein.\n') ...
];
end

function s = footer_block()
s = sprintf('\\end{document}\n');
end

% ============================================================ %
%  U1 section (narrower 9-col layout; USC doesn't compute Mean Dir/Lobe/ZS)
% ============================================================ %
function s = u1_section(csv_path, freq_label, lbl, caption)
T = readtable(csv_path, 'PreserveVariableNames', true);
vn = T.Properties.VariableNames;
extra = ismember(vn, {'PL_X'});
if any(extra); T(:, extra) = []; end
nRows = height(T);
tx_list = cellfun(@(v) char_from(v), T.(T.Properties.VariableNames{2}), 'UniformOutput', false);
tx_list = fillfwd(tx_list);
unique_tx = uniq_preserve(tx_list);

lines = {};
lines{end+1} = '\renewcommand{\arraystretch}{1.1}';
lines{end+1} = '\begin{table*}[!t]';
lines{end+1} = '\centering';
lines{end+1} = '\color{black}';
lines{end+1} = sprintf('\\caption{%s}', caption);
lines{end+1} = '\vspace{-0.2cm}';
lines{end+1} = '\begin{tabular}{p{0.8 cm}p{0.6 cm}p{0.6 cm}p{0.8 cm}p{0.8 cm}p{0.9 cm}p{0.9 cm}p{0.9 cm}p{0.9 cm}}';
lines{end+1} = '\hline';
lines{end+1} = ['\multicolumn{1}{p{0.8 cm}}{\textbf{Freq.}} & \textbf{TX} & \textbf{RX} & \textbf{Loc.} & ' ...
    '\multicolumn{1}{p{0.8 cm}}{\textbf{TR Sep.}} & ' ...
    '\multicolumn{1}{p{0.9 cm}}{\textbf{Omni PL}} & ' ...
    '\multicolumn{1}{p{0.9 cm}}{\textbf{Omni DS}} & ' ...
    '\multicolumn{1}{p{0.9 cm}}{\textbf{Omni ASA}} & ' ...
    '\multicolumn{1}{p{0.9 cm}}{\textbf{Omni ASD}} \\'];
lines{end+1} = '\hline';
lines{end+1} = '\text{[GHz]}& & & &[m]&[dB]&[ns]&[$^\circ$]&[$^\circ$] \\';
lines{end+1} = '\hline';

first_row_of_table = true;
for iTX = 1:numel(unique_tx)
    tx = unique_tx{iTX};
    idx = find(strcmp(tx_list, tx));
    nsub = numel(idx);
    for k = 1:nsub
        i = idx(k);
        row = T(i, :);
        rx = char_from(row.(vn{3}));
        loc = char_from(row.(vn{4}));
        tr = row.(vn{5}); tr_s = num_str(tr, '%.2f');
        % Columns 6 (PL), 8 (Omni DS), 10 (Omni ASA), 12 (Omni ASD) from N1 layout
        pl_s  = num_str(row.(vn{6}),  '%.2f');
        ds_s  = num_str(row.(vn{8}),  '%.2f');
        asa_s = num_str(row.(vn{10}), '%.2f');
        asd_s = num_str(row.(vn{12}), '%.2f');
        if k == 1
            if first_row_of_table
                lead = sprintf('\\multirow{%d}{*}{\\textbf{%s}} & \\multirow{%d}{*}{%s}', nRows, freq_label, nsub, tx);
                first_row_of_table = false;
            else
                lead = sprintf(' & \\multirow{%d}{*}{%s}', nsub, tx);
            end
            lines{end+1} = sprintf('%s & %s & %s & %s & %s & %s & %s & %s \\\\', lead, rx, loc, tr_s, pl_s, ds_s, asa_s, asd_s); %#ok<AGROW>
        else
            lines{end+1} = sprintf(' & & %s & %s & %s & %s & %s & %s & %s \\\\', rx, loc, tr_s, pl_s, ds_s, asa_s, asd_s); %#ok<AGROW>
        end
    end
    if iTX < numel(unique_tx); lines{end+1} = '\cline{2-9}'; end %#ok<AGROW>
end
lines{end+1} = '\hline';
lines{end+1} = '\end{tabular}%';
lines{end+1} = sprintf('\\label{tab:%s}%%', lbl);
lines{end+1} = '\vspace{-10pt}';
lines{end+1} = '\end{table*}%';
s = strjoin(lines, sprintf('\n'));
end


% ============================================================ %
%  N1 section (tab:LSPs layout — 16 cols, no gray shading)
% ============================================================ %
function s = n1_section(csv_path, freq_label, lbl, caption)
T = readtable(csv_path, 'PreserveVariableNames', true);
% N1 @ 6.75 GHz has an extra PL_X column that N1 @ 142 lacks. Drop it so
% the 16-column table layout is consistent across bands.
vn = T.Properties.VariableNames;
extra = ismember(vn, {'PL_X'});
if any(extra)
    T(:, extra) = [];
end
nRows = height(T);
% Group by TX for multirow
vn = T.Properties.VariableNames;
tx_list = cellfun(@(v) char_from(v), T.(vn{2}), 'UniformOutput', false);
tx_list = fillfwd(tx_list);
unique_tx = uniq_preserve(tx_list);

lines = {};
lines{end+1} = '\renewcommand{\arraystretch}{1.1}';
lines{end+1} = '\begin{table*}[!t]';
lines{end+1} = '\centering';
lines{end+1} = '\color{black}';
lines{end+1} = sprintf('\\caption{%s}', caption);
lines{end+1} = '\vspace{-0.2cm}';
lines{end+1} = '\begin{tabular}{p{0.6 cm}p{0.5 cm}p{0.5 cm}p{0.69 cm}p{0.6 cm}p{0.69 cm}p{0.69 cm}p{0.69 cm}p{0.69 cm}p{0.69 cm}p{0.69 cm}p{0.69 cm}p{0.6 cm}p{0.6 cm}p{0.6 cm}p{0.6 cm}}';
lines{end+1} = '\hline';
lines{end+1} = ['\multicolumn{1}{p{0.6 cm}}{\textbf{Freq.}} & \textbf{TX} & \textbf{RX} & \textbf{Loc.} & ' ...
    '\multicolumn{1}{p{0.6 cm}}{\textbf{TR Sep.}} & ' ...
    '\multicolumn{1}{p{0.69 cm}}{\textbf{PL}} & ' ...
    '\multicolumn{1}{p{0.69 cm}}{\textbf{Mean Dir. DS}} & ' ...
    '\multicolumn{1}{p{0.69 cm}}{\textbf{Omni DS}} & ' ...
    '\multicolumn{1}{p{0.69 cm}}{\textbf{Mean Lobe ASA}} & ' ...
    '\multicolumn{1}{p{0.69 cm}}{\textbf{Omni ASA}} & ' ...
    '\multicolumn{1}{p{0.69 cm}}{\textbf{Mean Lobe ASD}} & ' ...
    '\multicolumn{1}{p{0.69 cm}}{\textbf{Omni ASD}} & ' ...
    '\multicolumn{1}{p{0.6 cm}}{\textbf{Mean Lobe ZSA}} & ' ...
    '\multicolumn{1}{p{0.6 cm}}{\textbf{Omni ZSA}} & ' ...
    '\multicolumn{1}{p{0.6 cm}}{\textbf{Mean Lobe ZSD}} & ' ...
    '\multicolumn{1}{p{0.6 cm}}{\textbf{Omni ZSD}} \\'];
lines{end+1} = '\hline';
lines{end+1} = '\text{[GHz]}& & & &[m]&[dB]&[ns]&[ns]&[$^\circ$]&[$^\circ$]&[$^\circ$]&[$^\circ$]&[$^\circ$]&[$^\circ$]&[$^\circ$]&[$^\circ$] \\';
lines{end+1} = '\hline';

first_row_of_table = true;
for iTX = 1:numel(unique_tx)
    tx = unique_tx{iTX};
    idx = find(strcmp(tx_list, tx));
    nsub = numel(idx);
    for k = 1:nsub
        i = idx(k);
        row = T(i, :);
        rx  = char_from(row.(vn{3}));
        loc = char_from(row.(vn{4}));
        tr  = row.(vn{5}); tr_s = num_str(tr, '%.2f');
        vals = table2array(row(:, 6:end));
        vs = strjoin(arrayfun(@fmt_num_1dp, vals, 'UniformOutput', false), ' & ');
        if k == 1
            if first_row_of_table
                lead = sprintf('\\multirow{%d}{*}{\\textbf{%s}} & \\multirow{%d}{*}{%s}', nRows, freq_label, nsub, tx);
                first_row_of_table = false;
            else
                lead = sprintf(' & \\multirow{%d}{*}{%s}', nsub, tx);
            end
            lines{end+1} = sprintf('%s & %s & %s & %s & %s \\\\', lead, rx, loc, tr_s, vs); %#ok<AGROW>
        else
            lines{end+1} = sprintf(' & & %s & %s & %s & %s \\\\', rx, loc, tr_s, vs); %#ok<AGROW>
        end
    end
    if iTX < numel(unique_tx)
        lines{end+1} = '\cline{2-16}'; %#ok<AGROW>
    end
end
lines{end+1} = '\hline';
lines{end+1} = '\end{tabular}%';
lines{end+1} = sprintf('\\label{tab:%s}%%', lbl);
lines{end+1} = '\vspace{-10pt}';
lines{end+1} = '\end{table*}%';
s = strjoin(lines, sprintf('\n'));
end

% ============================================================ %
%  Cross-processing section (U3/N3 layout, 17 cols, gray shade)
% ============================================================ %
function s = cross_section(csv_path, freq_label, lbl, method_names, caption, header_banner, sort_mode) %#ok<INUSD>
T = readtable(csv_path, 'PreserveVariableNames', true);
nRows = height(T);
vn = T.Properties.VariableNames;
tx_list = cellfun(@(v) char_from(v), T.(vn{2}), 'UniformOutput', false);
tx_list = fillfwd(tx_list);
unique_tx = uniq_preserve(tx_list);

lines = {};
lines{end+1} = '\begin{table*}[!t]';
lines{end+1} = '\centering';
lines{end+1} = '\renewcommand{\arraystretch}{1.15}';
lines{end+1} = '\setlength{\tabcolsep}{2pt}';
lines{end+1} = '{\footnotesize';
lines{end+1} = sprintf('\\caption{%s}', caption);
lines{end+1} = '\vspace{-5 pt}';
lines{end+1} = sprintf('\\label{tab:%s}', lbl);
% Paper's exact column spec with gray on the 3rd column of each metric group
cspec = ['|>{\centering\arraybackslash}p{0.045\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.045\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.05\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.05\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.045\textwidth}!{\vrule width 1.2pt}' ...
    '>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash\columncolor{gray!20}}p{0.042\textwidth}!{\vrule width 1.2pt}' ...
    '>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash\columncolor{gray!20}}p{0.042\textwidth}!{\vrule width 1.2pt}' ...
    '>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash\columncolor{gray!20}}p{0.042\textwidth}!{\vrule width 1.2pt}' ...
    '>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash}p{0.042\textwidth}' ...
    '|>{\centering\arraybackslash\columncolor{gray!20}}p{0.042\textwidth}!{\vrule width 1.2pt}'];
lines{end+1} = sprintf('\\begin{tabular}{%s}', cspec);
lines{end+1} = '\hline';
lines{end+1} = sprintf('\\multicolumn{17}{|c!{\\vrule width 1.2pt}}{Point-Data table implementing %s} \\\\', header_banner);
lines{end+1} = '\hline';
lines{end+1} = ['\multirow{2}{*}{\makecell[c]{Freq.\\ $[$GHz$]$}} & ' ...
    '\multirow{2}{*}{TX} & \multirow{2}{*}{RX} & ' ...
    '\multirow{2}{*}{\makecell[c]{Loc \\ Type}} & ' ...
    '\multirow{2}{*}{\makecell[c]{TR\\ Sep.\\ $[$m$]$}} & ' ...
    '\multicolumn{3}{c!{\vrule width 1.2pt}}{Omni PL [dB]} & ' ...
    '\multicolumn{3}{c!{\vrule width 1.2pt}}{Omni DS [ns]} & ' ...
    '\multicolumn{3}{c!{\vrule width 1.2pt}}{Omni ASA [$^\circ$]} & ' ...
    '\multicolumn{3}{c!{\vrule width 1.2pt}}{Omni ASD [$^\circ$]} \\'];
lines{end+1} = '\cline{6-17}';
m1 = method_names{1}; m2 = method_names{2}; m3 = method_names{3};
lines{end+1} = sprintf([' &  &  &  &  & %s & %s & %s & %s & %s & %s & ' ...
    '%s & %s & %s & %s & %s & %s \\\\'], m1,m2,m3,m1,m2,m3,m1,m2,m3,m1,m2,m3);
lines{end+1} = '\hline';

first_row_of_table = true;
for iTX = 1:numel(unique_tx)
    tx = unique_tx{iTX};
    idx = find(strcmp(tx_list, tx));
    nsub = numel(idx);
    for k = 1:nsub
        i = idx(k);
        row = T(i, :);
        rx  = char_from(row.(vn{3}));
        loc = char_from(row.(vn{4}));
        tr  = row.(vn{5}); tr_s = num_str(tr, '%.2f');
        vals = table2array(row(:, 6:end));
        vs = strjoin(arrayfun(@fmt_num_2dp, vals, 'UniformOutput', false), ' & ');
        if k == 1
            if first_row_of_table
                lead = sprintf('\\multirow{%d}{*}{\\textbf{%s}} & \\multirow{%d}{*}{%s}', nRows, freq_label, nsub, tx);
                first_row_of_table = false;
            else
                lead = sprintf(' & \\multirow{%d}{*}{%s}', nsub, tx);
            end
            lines{end+1} = sprintf('%s & %s & %s & %s & %s \\\\', lead, rx, loc, tr_s, vs); %#ok<AGROW>
        else
            lines{end+1} = sprintf(' & & %s & %s & %s & %s \\\\', rx, loc, tr_s, vs); %#ok<AGROW>
        end
    end
    % Separator between TX groups: use \cline{2-17} (skips col 1) so the
    % Freq column's multirow cell stays visually continuous. The final
    % \hline at table end still spans all columns (closes the table).
    if iTX < numel(unique_tx)
        lines{end+1} = '\cline{2-17}'; %#ok<AGROW>
    end
end
lines{end+1} = '\hline';
lines{end+1} = '\end{tabular}';
lines{end+1} = '}';
lines{end+1} = '\vspace{-10 pt}';
lines{end+1} = '\end{table*}';
s = strjoin(lines, sprintf('\n'));
end

% -------- helpers --------
function out = char_from(v)
if iscell(v), out = char(v{1});
elseif isstring(v), out = char(v);
elseif isnumeric(v)
    if isnan(v), out = ''; else, out = sprintf('%g', v); end
else
    out = char(v);
end
if strcmpi(out, 'NaN'), out = ''; end
end

function out = num_str(v, fmt)
if isnumeric(v)
    if isnan(v), out = '--'; else, out = sprintf(fmt, v); end
else
    out = char_from(v);
    if isempty(out), out = '--'; end
end
end

function out = fmt_num_1dp(v)
out = num_str(v, '%.1f');
end

function out = fmt_num_2dp(v)
out = num_str(v, '%.2f');
end

function out = fillfwd(c)
last = '';
out = c;
for i = 1:numel(c)
    s = c{i};
    if isempty(s) || all(isspace(s))
        out{i} = last;
    else
        out{i} = s;
        last = s;
    end
end
end

function out = uniq_preserve(c)
seen = containers.Map('KeyType', 'char', 'ValueType', 'logical');
out = {};
for i = 1:numel(c)
    s = c{i};
    if ~isKey(seen, s)
        seen(s) = true;
        out{end+1} = s; %#ok<AGROW>
    end
end
end
