function generate_tex_row_blocks(target_path)
% generate_tex_row_blocks  Emit row-block snippets for main_final.tex tables.
%
%   Rather than rewriting main_final.tex (risky — multirow/multicolumn
%   structure is fragile), this produces copy-pasteable LaTeX row blocks
%   from our Processing CSVs. Open main_final.tex, locate the target
%   tabular, and replace the data rows between the header and \hline block.
%
%   Output file (target_path; defaults to docs/tex_row_blocks.tex):
%     * Block A  -- tab:RMSE_th  (Table VI)    from table06_rmse.csv
%     * Block B  -- tab:Stats_summ (Table VII) from table07_pooled_stats.csv
%     * Block C  -- tab:LSPs (Table IV partial) from table04_N1_142.csv
%                  (first 9 rows matching current paper partial)
%     * Block D  -- tab:U3_145  (partial)      from table08_U3_145.csv
%     * Block E  -- tab:U3_7    (partial)      from table09_U3_7.csv
%     * Block F  -- tab:N3_142  (partial)      from table10_N3_142.csv
%     * Block G  -- tab:N3_7    (partial)      from table11_N3_7.csv
%
%   For the full-tables supplement, use generate_supplement_tex.m instead.

if nargin < 1 || isempty(target_path)
    U = paths();
    target_path = fullfile(U.repo_root, 'docs', 'tex_row_blocks.tex');
end
U = paths();
csv_dir = U.out_dir;

fid = fopen(target_path, 'w');
if fid == -1, error('Cannot open %s', target_path); end

fprintf(fid, '%% AUTO-GENERATED by matlab/tools/generate_tex_row_blocks.m\n');
fprintf(fid, '%% Generated %s\n', datestr(now, 'yyyy-mm-dd HH:MM:SS'));
fprintf(fid, '%% Copy/paste the relevant block into main_final.tex.\n\n');

% --- Block A: Table VI RMSE (tab:RMSE_th) ---
fprintf(fid, '%%%%%% ===== Block A: tab:RMSE_th (Table VI) =====\n');
T = readtable(fullfile(csv_dir, 'table06_rmse.csv'));
for i = 1:height(T)
    fprintf(fid, '%s & %s & %.2f & %.2f & %.2f & %.2f \\\\\n', ...
        sanitize(char(T.Band(i))), sanitize(char(T.Metric(i))), ...
        T.USC_data_NYU_thres(i), T.USC_data_USC_thres(i), ...
        T.NYU_data_USC_thres(i), T.NYU_data_NYU_thres(i));
end
fprintf(fid, '\n');

% --- Block B: Table VII pooled stats ---
fprintf(fid, '%%%%%% ===== Block B: tab:Stats_summ (Table VII) =====\n');
path07 = fullfile(csv_dir, 'table07_pooled_stats.csv');
if exist(path07, 'file')
    fid_in = fopen(path07, 'r');
    raw = fread(fid_in, inf, 'uint8=>char')';
    fclose(fid_in);
    fprintf(fid, '%% Raw CSV (table07 structure varies; hand-edit as needed):\n');
    fprintf(fid, '%% %s', strrep(raw, sprintf('\n'), sprintf('\n%% ')));
    fprintf(fid, '\n');
end

% --- Blocks C-G: partial per-link tables ---
part_tables = {
    'C', 'tab:LSPs',    'table04_N1_142.csv'
    'D', 'tab:U3_145',  'table08_U3_145.csv'
    'E', 'tab:U3_7',    'table09_U3_7.csv'
    'F', 'tab:N3_142',  'table10_N3_142.csv'
    'G', 'tab:N3_7',    'table11_N3_7.csv'
};
for k = 1:size(part_tables, 1)
    fprintf(fid, '%%%%%% ===== Block %s: %s =====\n', part_tables{k, 1}, part_tables{k, 2});
    fprintf(fid, '%% Full rows; paste as many as fit within the paper page budget.\n');
    T = readtable(fullfile(csv_dir, part_tables{k, 3}), 'PreserveVariableNames', true);
    vn = T.Properties.VariableNames;
    last_freq = ''; last_tx = '';
    for i = 1:height(T)
        r = T(i, :);
        freq = char_from(r.(vn{1}));
        tx   = char_from(r.(vn{2}));
        rx   = char_from(r.(vn{3}));
        loc  = char_from(r.(vn{4}));
        tr_v = r.(vn{5});
        if isnumeric(tr_v), tr_s = sprintf('%.2f', tr_v); else, tr_s = char_from(tr_v); end
        vals = table2array(r(:, 6:end));
        if ~isempty(freq) && ~all(isspace(freq)), last_freq = freq; end
        if ~isempty(tx)   && ~all(isspace(tx)),   last_tx   = tx;   end
        vs = arrayfun(@fmt_cell, vals, 'UniformOutput', false);
        fprintf(fid, '%s & %s & %s & %s & %s & %s \\\\\n', ...
            sanitize(freq), sanitize(tx), sanitize(rx), sanitize(loc), tr_s, strjoin(vs, ' & '));
    end
    fprintf(fid, '\n');
end

fclose(fid);
fprintf('generate_tex_row_blocks: wrote %s\n', target_path);
end

function out = char_from(v)
if iscell(v),  out = char(v{1});
elseif isstring(v), out = char(v);
elseif isnumeric(v)
    if isnan(v), out = '';
    else, out = sprintf('%g', v); end
else, out = char(v);
end
if isempty(out) || strcmp(out, 'NaN'), out = ''; end
end

function out = fmt_cell(v)
if isnumeric(v)
    if isnan(v), out = '--'; else, out = sprintf('%.2f', v); end
else
    out = char(v);
    if isempty(out) || strcmp(out, 'NaN'), out = '--'; end
end
end

function out = sanitize(s)
out = strrep(char(s), '%', '\%');
out = strrep(out, '_', '\_');
end
