"""Compare Python vs. MATLAB port CSV outputs cell-by-cell.

After running both ports (`channel-run-all` in Python, `run_all` in MATLAB),
this script diffs the two sets of table CSVs and writes a markdown summary
to docs/matlab_python_diff.md.

Usage:
    python python/scripts/compare_ports.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
PY = REPO / "figures" / "python"
ML = REPO / "figures" / "matlab"
OUT = REPO / "docs" / "matlab_python_diff.md"

# Pairs of matching outputs. MATLAB CSVs with different column names / shapes
# get a specialized comparison so we can align them meaningfully.
PAIRS = [
    "table04_N1_142.csv",
    "table06_rmse.csv",
    "table07_pooled_stats.csv",
    "table08_U3_145.csv",
    "table09_U3_7.csv",
    "table10_N3_142.csv",
    "table11_N3_7.csv",
]


def _numeric_cells(df: pd.DataFrame):
    cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    return df[cols]


def compare_one(name: str, py_path: Path, ml_path: Path) -> list[str]:
    """Return markdown lines describing the diff between two CSVs."""
    out: list[str] = []
    out.append(f"## `{name}`\n")
    if not py_path.exists():
        out.append(f"- ❌ Python CSV missing: `{py_path}`\n")
        return out
    if not ml_path.exists():
        out.append(f"- ❌ MATLAB CSV missing: `{ml_path}` — run `matlab/run_all.m` first\n")
        return out
    p = pd.read_csv(py_path)
    m = pd.read_csv(ml_path)

    p_num = _numeric_cells(p)
    m_num = _numeric_cells(m)

    # Column-alignment strategy: intersect numeric column names.
    common = [c for c in p_num.columns if c in m_num.columns]
    py_only = [c for c in p_num.columns if c not in m_num.columns]
    ml_only = [c for c in m_num.columns if c not in p_num.columns]

    out.append(f"- Python rows: {len(p)}, MATLAB rows: {len(m)}")
    out.append(f"- Common numeric columns: {len(common)}")
    if py_only:
        out.append(f"- Python-only numeric columns: {py_only}")
    if ml_only:
        out.append(f"- MATLAB-only numeric columns: {ml_only}")

    if not common or len(p) != len(m):
        out.append(f"- ⚠️ Row count or column-set mismatch — manual inspection recommended.")
        out.append("")
        return out

    abs_diff = (p_num[common].values - m_num[common].values)
    abs_max = np.nanmax(np.abs(abs_diff)) if abs_diff.size else 0.0
    # Relative diff with safe denominator
    denom = np.maximum(np.abs(p_num[common].values), 1e-9)
    rel_diff = np.abs(abs_diff) / denom
    rel_max = np.nanmax(rel_diff) if rel_diff.size else 0.0

    status = (
        "✅ within tolerance"
        if abs_max < 0.05 or rel_max < 0.02
        else "⚠️ divergence > tolerance (inspect cells below)"
    )
    out.append(f"- Max |Δ| across numeric cells: **{abs_max:.4g}**")
    out.append(f"- Max relative Δ: **{rel_max:.4g}**  — {status}")

    if rel_max > 0.02 and abs_max > 0.05:
        # Find the top-5 worst cells for reporting
        flat_rel = rel_diff.flatten()
        idx = np.argsort(-flat_rel)[:5]
        out.append("")
        out.append("| Row | Column | Python | MATLAB | |Δ| | Δ/Py |")
        out.append("|-----|--------|--------|--------|-----|------|")
        for k in idx:
            if not np.isfinite(flat_rel[k]):
                continue
            r, c = divmod(int(k), len(common))
            col = common[c]
            row_key = p.iloc[r].to_dict()
            # Pick a tidy label from non-numeric columns
            lbl_parts = [f"{kk}={vv}" for kk, vv in row_key.items()
                         if kk not in common][:3]
            label = "; ".join(str(x) for x in lbl_parts)
            out.append(f"| {label} | {col} | {p_num[col].iloc[r]:.4g} | "
                       f"{m_num[col].iloc[r]:.4g} | {abs(abs_diff[r,c]):.4g} | "
                       f"{rel_diff[r,c]:.4g} |")
    out.append("")
    return out


def main() -> int:
    if not PY.exists():
        print(f"Python output directory missing: {PY}", file=sys.stderr)
        print("Run `python -m channel_analysis.run_all` first.", file=sys.stderr)
        return 1
    if not ML.exists():
        print(f"MATLAB output directory missing: {ML}", file=sys.stderr)
        print("Run `matlab/run_all.m` on a MATLAB-licensed machine first.", file=sys.stderr)
        return 1

    lines = ["# MATLAB ↔ Python port — cell-level diff report",
             "",
             "Generated by `python python/scripts/compare_ports.py`.",
             "Read alongside `docs/matlab_python_parity.md` for the port-level summary.",
             ""]
    for name in PAIRS:
        lines.extend(compare_one(name, PY / name, ML / name))

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
